services:
  postgres:
    image: postgres:17.5
    container_name: postgres_service
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_database:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:9.4
    container_name: pgadmin_service
    restart: always
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  postgres_database:
    driver: local
  pgadmin_data:
    driver: local
